[p2p]
moniker = "NamasStable"
identity = ""
seeds = "22b1f1040cc4462fb851a77b23902650125e7f4d@37.187.147.23:26656"
persistent_peers = "d756d8d108edf34eaaac0093f27dd2d10a35230d@213.199.63.145:26656,7106f8ecca9a9244f308cb713999bacfebf2d3d4@38.242.145.134:26656,a3fe7262301461ff69ed05d48650c8c99edebcc0@91.108.247.114:26656,76f5a8c98e621b9ac76dd5230ffb400cfef50bcd@184.174.33.181:26656,6d3d5b13e2f203dbf718d8c201e2af97bbc52dbe@45.84.138.149:26656,b681477a33ae49fe1976f08a526fcf471a5325d4@173.212.235.213:26656,c30142baa5ea8341c6644b79deb9f132b2bb0270@185.245.61.115:26656,0a09e1e1c96f3e8be3204bf10d35ac64294ca826@109.199.108.76:26656,c10733befce4568ad30c5d4e64fd993572440f45@185.245.61.109:26656,f0f05c08acd376beb61837987e29b98e10a53b63@89.222.124.13:26656,019aa7fc68223c8b13a8966621dc70d3817d2570@185.232.70.33:26656,d726ae605a468b77394e04d82ce7b9133b87e0e9@149.102.134.42:26656,48514b354e0163dd439e71a92fa91eae713c3eee@194.163.136.85:26656,8caf1b8d734d3787619989ab75bb668913bf5e53@84.46.240.92:26656,1161837fa4d97293a387ee351200a1021c09e218@155.133.23.172:26656,078e122f1a16e3a7f4f08c942fb6d80ff13377d6@184.174.36.61:26656,21e969c275e5fd111fe9df20d1e10a357b64de39@51.77.81.3:26656,d990e518379226990e2fd0b4787e22bcbeb5f6e5@38.242.249.254:26656,9723553ab6ec3869bbfacc12f64321e3a056d1d5@109.199.100.113:26656,b74b5f566b37e6af6c3bd0aa8111ff50b256fcc1@194.163.170.176:26656,d21956e0fa1b723cd8217146f21b4840bf10c200@207.180.230.81:26656"
external_address = ""
addr_book_strict = false
max_num_inbound_peers = 80
max_num_outbound_peers = 50
allow_duplicate_ip = false
handshake_timeout = "20s"
dial_timeout = "3s"
pex = true
filter_peers = false

[rpc]
laddr = "tcp://0.0.0.0:26657"
grpc_laddr = ""
unsafe = false
max_open_connections = 900

[mempool]
type = ""
recheck = true
broadcast = true
size = 5000
max_txs_bytes = 1073741824
cache_size = 10000

[statesync]
enable = false
trust_height = 0
trust_hash = ""
trust_period = "168h0m0s"
rpc_servers = ""

[indexer]
indexer = "null"

[instrumentation]
prometheus = false
prometheus_listen_addr = ":26660"
max_open_connections = 3
namespace = "cometbft"
